### ISSUE TITLE
Register a new package

### ISSUE THREAD

**Issue by RexWzh** [JuliaImages/QRDecoders.jl#8]
@JuliaRegistrator branch=master

**Comment by RexWzh** [comment]
@JuliaRegistrator branch=master

**Comment by RexWzh** [comment]
I just fix the compact helper, hope it could work :rofl: 
@JuliaRegistrator branch=master

**Comment by johnnychen94** [comment]
@JuliaRegistrator register branch=master

**Comment by johnnychen94** [comment]
@RexWzh Looks like you missed the `register` 😆
